baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

excerpt_separator:  '<!-- more -->'

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages
 
# Tags
# tag_page_dir:         tag
# tag_page_layout:      tag_page
# tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


gitalk:
  enable: true
  owner: wsdydeni
  repo: wsdydeni.github.io
  clientID: 5ba623a6d85f6c769ba1
  clientSecret: b5a11d32fa5613e027d9463a19c49e1f0813a079
  admin: wsdydeni
