#-------------------------------
# General Site Settings
title: 无伤大雅的你呀
logo:  # You can add own logo.
description: 个人博客


#-------------------------------
# Author Settings
author:
  name: 无伤大雅的你呀
  image: owl.jpg
  say-hello: 你好, 我是 <strong>无伤大雅的你呀</strong>
  bio: 欢迎来到我的个人博客


#-------------------------------
# Contact links
juejin: https://juejin.cn/user/1521379824381357/posts # Add your 掘金 handle
wechat: weixin://profile/gh_a9ab84416a7a # Add your 微信公众号 handle
mail: wsdyeniya@qq.com # Add your 邮箱 handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
